<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>


<h3> Get to Know a Numpy Array </h3>


You will use the numpy array <code>A</code> for the following questions.


In [2]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) Find the type of `x` using the function `type()`.


In [3]:
type(A)

numpy.ndarray

<details><summary>Click here for the solution</summary>

```python
type(A)
```

</details>


2) Find the shape of the array:


In [4]:
A.shape

(3, 2)

<details><summary>Click here for the solution</summary>

```python
A.shape
```

</details>


3) Find the type of data in the array:


In [5]:
A.dtype

dtype('int32')

<details><summary>Click here for the solution</summary>

```python
A.dtype
```

</details>


4) Find the second row of the numpy array <code>A</code>:


In [6]:
A[1]

array([21, 22])

<details><summary>Click here for the solution</summary>

```python
A[1]
```

</details>


<h3>Two Types of Multiplication</h3>


You will use the following numpy arrays for the next questions: 


In [7]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) Multiply array <code>A</code> and <code>B</code>.


In [8]:
C = A * B
C

array([[11,  0],
       [ 0, 22]])

<details><summary>Click here for the solution</summary>

```python
C = A * B
C
```

</details>


2)  Perform matrix multiplication on array <code>A</code> and <code>B</code> (order will not matter in this case).


In [9]:
Z = np.dot(A,B)
Z

array([[11, 12],
       [21, 22]])

<details><summary>Click here for the solution</summary>

```python
Z = np.dot(A,B)
Z
```

</details>


<hr>

<h3>Questions about Numpy 2D Arrays (External resource)</h3>

<h3>QUESTION 1</h3>

How many rows are in the following numpy array?

In [11]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<h3>QUESTION 2</h3>

Is it possible to perform the following operation?

In [14]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = np.dot(A,B)
result

<class 'ValueError'>: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
